# Generated by Django 4.2.3 on 2023-10-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersystem',
            name='name',
        ),
        migrations.AlterField(
            model_name='usersystem',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_usersystem_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='usersystem',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
