# Generated by Django 4.2.3 on 2023-10-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usersystem_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersystem',
            old_name='username',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='usersystem',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
